### ISSUE TITLE
How do people feel about using ASP.NET 5 MVC 6?

### ISSUE THREAD

**Issue by tparnell8** [tparnell8/CS6440#1]

**Comment by waryzh** [comment]
I'd certainly like to try this latest version, though I have not used them.

**Comment by dbcarey** [comment]
I'm not an asp.net person, but I'll do whatever is needed (testing, presentation, documentation).  I have no objections.

**Comment by codesoftly** [comment]
My only concern with this is if the TAs have to rebuild our solution. I've had significant issues in the OMSCS building projects with unreleased technologies (specifically Android SDK - which was in an RC build).

**Comment by tparnell8** [comment]
thats actually a really good point.. I'm not sure they are planning to compile these things as they didn't put a restriction on the language, but perhaps sticking with the 4.x branch might be a smarter way to go just incase.

**Comment by tparnell8** [comment]
I'm going to close this...I think @codesoftly's point is really good and thus I think we should just stick on 4.6.1 MVC 5 just to make sure there are no compilation issues
